#!/usr/bin/env python
# coding: utf-8
# @Time     : 2025/8/20 10:20
# @Author   : guoqun X2590
# @FileName : trans_unicode.py
# @Project  : DataForge


import json
import uuid

from loguru import logger

from common.initialization import setup_logging
from config import PROJECT_PATH
from utils.log import LogManager, TracedLogger

log_config = LogManager(
    base_path=str(PROJECT_PATH.absolute()),
    log_path="logs",
    log_name="debug.log",
    file_log_level="TRACE",
)
setup_logging(log_config.get_config().get("handlers"))

traced_logger = TracedLogger()

trace_uuid = uuid.uuid4().hex

logger.info(f"trace_uuid: {trace_uuid} ")

token = traced_logger.set_trace_uuid(trace_uuid)


from server.api.routers.task import compare_task_rule

test_left = [
    {
        "col": 1,
        "args": {},
        "name": "",
        "cname": "标识ID",
        "ename": "MD_ID",
        "value": "3e59c7f4-f6dd-11ee-b6de-0242bcbd0005_492_991C1316_20250607043201_cffceae4d5174abeb397e1590d523434jv3on2",
        "preview": "score: 98, reason: 字段英文名为'MD_ID'，示例数据'3e59c7f4-f6dd-11ee-b6de-0242bcbd0005_492_991C1316_20250607043201_cffceae4d5174abeb397e1590d523434jv3on2'包含标准UUID格式的分段结构（如'3e59c7f4-f6dd-11ee-b6de-0242bcbd0005'），且整体长度和字符模式与UUID高度一致，与<configs>中'UUID'条目匹配。",
        "category": "UUID",
    },
    {
        "col": 2,
        "args": {},
        "name": "",
        "cname": "来源系统",
        "ename": "COL_SOUR_SYS",
        "value": "129",
        "preview": "score: 90, reason: 字段示例数据为'129'，仅包含数字，且字段描述为'数据采集来源系统'，结合字段类型为string，虽可能表示系统编号，但无明确标识符特征（如身份证、车牌号等），与预定义类别中'数字串'的特征（如'264280'）高度一致，因此推荐为'数字串'，置信度较高。",
        "category": "数字串",
    },
    {
        "col": 3,
        "args": {},
        "name": "",
        "cname": "来源系统备注",
        "ename": "COL_SOUR_SYS_REMARK",
        "value": "",
        "preview": "score: 85, reason: 字段名为'来源系统备注'，类型为string，示例数据为空，但根据其命名和用途（系统备注）推测可能包含非结构化、无固定格式的文本内容，与<configs>中'随机串'条目（如'出现这样当前以及.'）在语义上相似，均表示非标准化的文本描述，因此推荐为'随机串'，置信度较高但非完全确定。",
        "category": "随机串",
    },
    {
        "col": 4,
        "args": {},
        "name": "",
        "cname": "来源部门",
        "ename": "COL_SOUR_DEP",
        "value": "1006",
        "preview": "score: 85, reason: 字段示例数据为'1006'，为纯数字串，且字段名称'来源部门'与'数据资源来源类型代码'暗示其为某种编码或标识符。虽然'1006'可能为特定编码，但其形式为四位数字，与'随机主键'在<configs>中定义的示例'c1331fd2af684b20857198c3a07a3764'虽不完全一致，但均属于无明显语义的数字或字符编码。结合字段类型为string且无明确业务含义，更倾向归类为'随机主键'而非其他具有明确语义的类别（如公司编号、单位编号等），故推荐为'随机主键'，置信度较高。",
        "category": "随机主键",
    },
    {
        "col": 5,
        "args": {},
        "name": "",
        "cname": "来源表名",
        "ename": "COL_SOUR_TABLE",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'来源表名'，字段类型为string，示例数据为空，但根据字段名称和常见数据特征，'来源表名'通常为数据库中表的名称，如'customer_info'、'order_table'等，这类名称通常为无固定语义的命名，符合'随机串'类别中'出现这样当前以及.'这类无规律字符串的特征，且在<configs>中'随机串'的示例值为无特定语义的中文字符组合，与'来源表名'的命名模式一致，因此推荐为'随机串'类别。",
        "category": "随机串",
    },
    {
        "col": 6,
        "args": {},
        "name": "",
        "cname": "来源地",
        "ename": "COL_SOUR_PLAC",
        "value": "330100",
        "preview": "score: 85, reason: 字段示例数据'330100'为6位数字编码，符合行政区划编码特征；'33'代表浙江省，'330100'代表杭州市，属于省级以下行政区划编码，与'省份'类别在语义和数据模式上高度匹配；虽'省份'在configs中示例为'吉林省'，但该字段为编码形式，更符合行政区划编码的范畴，而'省份'是唯一接近的预定义类别。",
        "category": "省份",
    },
    {
        "col": 7,
        "args": {},
        "name": "",
        "cname": "采集时间",
        "ename": "COLL_TIME",
        "value": "1749241991",
        "preview": "score: 98, reason: 字段名为'COLL_TIME'，示例数据'1749241991'为一个较大的整数，符合时间戳的特征；该值与<configs>中'当前时间绝对秒'的示例值'1749106269'在数值范围和格式上高度一致，且'当前时间绝对秒'对应的是从1970年1月1日以来的秒数，符合时间戳的定义，因此推荐为'当前时间绝对秒'。",
        "category": "当前时间绝对秒",
    },
    {
        "col": 8,
        "args": {},
        "name": "",
        "cname": "原始系统主键",
        "ename": "ORIG_DATA_ID",
        "value": "5ce85f5c12604a88b78c013beaccaabb",
        "preview": "score: 98, reason: 字段示例数据'5ce85f5c12604a88b78c013beaccaabb'为32位十六进制字符串，符合随机主键的特征，与<configs>中'随机主键'条目完全匹配，且该字段为原始系统主键，通常用于唯一标识记录，符合随机主键的典型用途。",
        "category": "随机主键",
    },
    {
        "col": 9,
        "args": {},
        "name": "",
        "cname": "更新时间",
        "ename": "UPD_TIME",
        "value": "1749264892",
        "preview": "score: 98, reason: 字段名为'UPD_TIME'，示例数据'1749264892'为一个较大的整数，符合时间戳的特征；结合'更新时间'的语义，表示自1970年1月1日以来的秒数，与<configs>中'当前时间绝对秒'的示例值'1749106269'高度一致，属于标准的时间戳格式，因此最匹配的类别是'当前时间绝对秒'。",
        "category": "当前时间绝对秒",
    },
    {
        "col": 10,
        "args": {},
        "name": "",
        "cname": "是否删除",
        "ename": "INFO_DELE_JUDGE_FLAG",
        "value": "0",
        "preview": "score: 90, reason: 字段示例数据为'0'，属于纯数字字符串，且字段名为'是否删除'，通常用于标识状态，'0'表示未删除，'1'表示已删除，符合数字串的特征。虽然存在'是否'类字段可能对应布尔值，但示例数据仅为'0'，且类型为string，更符合数字串的模式，而非布尔或其它类别。",
        "category": "数字串",
    },
    {
        "col": 11,
        "args": {},
        "name": "",
        "cname": "人员编号",
        "ename": "PERSON_NO",
        "value": "331123200007283693",
        "preview": "score: 95, reason: 字段示例数据'331123200007283693'为18位数字，符合中国身份证号码的格式特征（前6位为地区码，第7-14位为出生日期，第15-17位为顺序码，第18位为校验码），且字段中文名为'人员编号'，在实际业务中常用于标识个人身份，与'身份证'类别高度匹配。",
        "category": "身份证",
    },
    {
        "col": 12,
        "args": {},
        "name": "",
        "cname": "姓名",
        "ename": "NAME",
        "value": "胡秀梅",
        "preview": "score: 98, reason: 字段中文名为'姓名'，英文名为'NAME'，数据类型为string，示例数据'胡秀梅'为典型的中文姓名，与<configs>中'姓名'条目的语义和示例值完全匹配。",
        "category": "姓名",
    },
    {
        "col": 13,
        "args": {},
        "name": "",
        "cname": "姓名拼音",
        "ename": "NAME_SPELL",
        "value": "huxiumei",
        "preview": "score: 98, reason: 字段中文名为'姓名拼音'，英文名为'NAME_SPELL'，示例数据为'huxiumei'，符合姓名拼音的常见格式，与<configs>中'姓名拼音'条目完全匹配。",
        "category": "姓名拼音",
    },
    {
        "col": 14,
        "args": {},
        "name": "",
        "cname": "性别代码",
        "ename": "SEX",
        "value": "1",
        "preview": "score: 98, reason: 字段中文名为'性别代码'，英文名为'SEX'，示例数据为'1'，符合性别编码的常见模式（如1表示男性，0表示女性），与<configs>中'性别'条目的语义和示例值（'男'）高度一致，尽管示例为数字编码，但其语义指向'性别'类别，且该类别在配置中明确存在。",
        "category": "性别",
    },
    {
        "col": 15,
        "args": {},
        "name": "",
        "cname": "性别",
        "ename": "SEX_DESIG",
        "value": "",
        "preview": "score: 98, reason: 字段中文名为'性别'，英文名为'SEX_DESIG'，数据类型为string，符合'性别'类别的语义特征。预定义配置中'性别'的value为'男'，与该字段的语义完全一致，且字段名与配置项高度匹配。",
        "category": "性别",
    },
    {
        "col": 16,
        "args": {},
        "name": "",
        "cname": "出生日期",
        "ename": "BIRTH_DATE",
        "value": "20000728",
        "preview": "score: 98, reason: 字段中文名为'出生日期'，英文名为'BIRTH_DATE'，示例数据为'20000728'，格式为YYYYMMDD，无分隔符，与<configs>中'日期-2'条目（值为'19790809'）完全一致，符合无分隔符的8位数字日期格式，因此最匹配的类别是'日期-2'。",
        "category": "日期-2",
    },
    {
        "col": 17,
        "args": {},
        "name": "",
        "cname": "身份证号",
        "ename": "CERT_NO",
        "value": "331123200007283693",
        "preview": "score: 98, reason: 字段中文名为'身份证号'，英文名为'CERT_NO'，示例数据'331123200007283693'为18位数字，符合中国身份证号码的编码规则（前6位为地区码，第7-14位为出生日期，第15-17位为顺序码，第18位为校验码），与<configs>中'身份证'条目完全匹配。",
        "category": "身份证",
    },
    {
        "col": 18,
        "args": {},
        "name": "",
        "cname": "体貌特征",
        "ename": "PHYSICAL_FEAT_DESC",
        "value": "不断感觉人员大家位置.原因游戏当然状态环境.次数更多价格研究.研究重要通过搜索帖子.",
        "preview": "score: 90, reason: 字段中文名为'体貌特征'，但示例数据'不断感觉人员大家位置.原因游戏当然状态环境.次数更多价格研究.研究重要通过搜索帖子.'为无明确语义的中文短语拼接，不具备具体结构特征，且与预定义类别中的'体貌特征'无关；其内容为无规律的中文片段组合，与'随机串'类别（如'出现这样当前以及.'）的语义和模式高度一致，因此推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 19,
        "args": {},
        "name": "",
        "cname": "国籍代码",
        "ename": "NATION_CODE",
        "value": "CHN",
        "preview": "score: 90, reason: 字段中文名为'国籍代码'，英文名为'NATION_CODE'，描述为'国家和地区字母代码（三字母）'，示例数据'CHN'是国家三字母代码，与<configs>中'国籍'条目的示例'柬埔塞'在语义上一致，尽管'CHN'是代码而非国家名称，但'国籍'类别在配置中明确指向国家信息，且'CHN'是'中国'的国际标准三字母代码，因此最匹配。",
        "category": "国籍",
    },
    {
        "col": 20,
        "args": {},
        "name": "",
        "cname": "国籍",
        "ename": "NATION_NAME",
        "value": "",
        "preview": "score: 98, reason: 字段中文名为'国籍'，英文名为'NATION_NAME'，数据类型为string，与<configs>中'国籍'条目的语义和命名完全一致，且示例数据应为国家名称，符合'国籍'类别的定义。",
        "category": "国籍",
    },
    {
        "col": 21,
        "args": {},
        "name": "",
        "cname": "民族代码",
        "ename": "NATION",
        "value": "42",
        "preview": "score: 90, reason: 字段名为'民族代码'，示例数据为'42'，为纯数字字符串，且字段类型为string，虽与'民族'类别相关，但'民族'在<configs>中对应的是'哈萨克族'等具体民族名称，而非数字代码。因此该字段实际为民族的代码标识，属于数字编码，最匹配的预定义类别是'数字串'，置信度较高。",
        "category": "数字串",
    },
    {
        "col": 22,
        "args": {},
        "name": "",
        "cname": "民族",
        "ename": "NATION_DESIG",
        "value": "",
        "preview": "score: 98, reason: 字段中文名为'民族'，字段类型为string，与<configs>中'民族'条目的语义完全一致，且该类别在配置中明确包含示例值'哈萨克族'，与字段语义高度匹配。",
        "category": "民族",
    },
    {
        "col": 23,
        "args": {},
        "name": "",
        "cname": "工作单位",
        "ename": "WORK_UNIT_COMP_NAME",
        "value": "超艺",
        "preview": "score: 90, reason: 字段中文名为'工作单位'，英文名为'WORK_UNIT_COMP_NAME'，类型为string，示例数据'超艺'符合公司名称的命名特征，且在<configs>中'公司名称'的示例值'新宇龙信息传媒有限公司'与'超艺'在语义和结构上一致，均为企业实体名称，因此推荐为'公司名称'类别。",
        "category": "公司名称",
    },
    {
        "col": 24,
        "args": {},
        "name": "",
        "cname": "学历代码",
        "ename": "EDUC_LEVE_CODE",
        "value": "80",
        "preview": "score: 98, reason: 字段名为'学历代码'，示例数据为'80'，为纯数字字符串，且无明显语义指向如年龄、日期、编号等具体类别。虽然'学历代码'具有业务含义，但在预定义类别中无直接匹配项，最接近的类别为'数字串'，因其仅包含数字且无特殊格式或语义，置信度高。",
        "category": "数字串",
    },
    {
        "col": 25,
        "args": {},
        "name": "",
        "cname": "文化程度",
        "ename": "EDUC_LEVE_NAME",
        "value": "",
        "preview": "score: 0, reason: 字段名为'文化程度'，其值应为如'本科'、'硕士'等描述性文本，属于枚举类型或字典值，但提供的示例数据为空，无法匹配任何预定义类别。在<configs>中无对应类别如'文化程度'或类似描述，且无有效示例数据支持其他类别的判断，因此无法确定准确类别，置信度为0，推荐为'数字串'作为兜底处理。",
        "category": "数字串",
    },
    {
        "col": 26,
        "args": {},
        "name": "",
        "cname": "户籍地代码",
        "ename": "DOMIC_ADDI_CODE",
        "value": "331123",
        "preview": "score: 85, reason: 字段名为'户籍地代码'，示例数据'331123'为6位数字，符合行政区划代码的特征，且'33'代表浙江省，与'省份'类别中'吉林省'的示例数据在类型和语义上一致，虽然具体值不同，但该字段属于行政区划编码范畴，与'省份'类别在数据类型和业务含义上高度匹配。",
        "category": "省份",
    },
    {
        "col": 27,
        "args": {},
        "name": "",
        "cname": "户籍地址",
        "ename": "DOMIC_ADMIN_NAME",
        "value": "",
        "preview": "score: 90, reason: 字段中文名为'户籍地址'，明确指向地址信息；字段类型为string，示例数据虽为空，但结合上下文语义，该字段用于存储户籍所在地的详细地址，与<configs>中'地址'类别的语义完全一致，且'地址'的示例值'江苏省徐州市泉山区金江街道汉中路604号'为典型地址格式，匹配度高。",
        "category": "地址",
    },
    {
        "col": 28,
        "args": {},
        "name": "",
        "cname": "户籍地区县代码",
        "ename": "DOMIC_OWN_COUN_ADDI_CODE",
        "value": "",
        "preview": "score: 0, reason: 字段示例数据为空，无法根据数据内容判断其类别；字段名为'户籍地区县代码'，虽与行政区划相关，但无具体示例数据支持其为特定类别（如省份、城市等），且在<configs>中无直接匹配的类别，因此无法确定其具体类别，置信度为0，返回默认类别'数字串'。",
        "category": "数字串",
    },
    {
        "col": 29,
        "args": {},
        "name": "",
        "cname": "户籍地区县",
        "ename": "DOMIC_OWN_COUN_ADMIN_NAME",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'户籍地区县'，表示户籍所在的县级行政区划，属于地理位置信息；字段类型为string，示例数据虽为空，但结合语义和预定义配置中'地址'类别（如'江苏省徐州市泉山区金江街道汉中路604号'）的范围，'户籍地区县'属于地址信息的组成部分，因此最匹配的类别是'地址'。虽然更细粒度的'省份'或'城市'也相关，但'地址'是涵盖此类信息的最恰当大类，置信度较高。",
        "category": "地址",
    },
    {
        "col": 30,
        "args": {},
        "name": "",
        "cname": "户籍地详址",
        "ename": "DOMIC_ADDR_NAME",
        "value": "云南省倩县六枝特高路N座 811821",
        "preview": "score: 90, reason: 字段中文名为'户籍地详址'，英文名为'DOMIC_ADDR_NAME'，表示户籍所在地的详细地址，类型为string，示例数据'云南省倩县六枝特高路N座 811821'包含省、县、道路名称及门牌号，符合详细地址的特征；在<configs>中'地址'类别对应的示例值为'江苏省徐州市泉山区金江街道汉中路604号'，语义和格式高度一致，因此推荐为'地址'类别。",
        "category": "地址",
    },
    {
        "col": 31,
        "args": {},
        "name": "",
        "cname": "居住地区县代码",
        "ename": "RESID_OWN_COUN_ADDI_CODE",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'居住地区县代码'，英文名为'RESID_OWN_COUN_ADDI_CODE'，描述为行政区划，属于地址相关编码。虽然其值为代码形式，但结合上下文属于行政区划编码的范畴，与'地址类型'类别在语义上最为接近，且<configs>中'地址类型'的value为'其它'，表明其可涵盖此类非具体地址但属于地理行政区划代码的字段。虽无直接匹配的示例，但其语义与'地址类型'最契合。",
        "category": "地址类型",
    },
    {
        "col": 32,
        "args": {},
        "name": "",
        "cname": "居住地区县",
        "ename": "RESID_OWN_COUN_ADMIN_NAME",
        "value": "",
        "preview": "score: 90, reason: 字段中文名为'居住地区县'，表明该字段描述的是居住地的行政区划信息，与'地址'类别中的'街道地址'、'房屋地址'等具有相同语义范畴；虽然示例数据为空，但根据字段名和上下文语义，其指向的是地理地址信息，与<configs>中'地址'类别（如'江苏省徐州市泉山区金江街道汉中路604号'）在语义上高度一致，因此推荐为'地址'类别。",
        "category": "地址",
    },
    {
        "col": 33,
        "args": {},
        "name": "",
        "cname": "居住地详址",
        "ename": "RESID_ADDR_NAME",
        "value": "辽宁省梧州市南湖刘街B座 132736",
        "preview": "score: 90, reason: 字段中文名为'居住地详址'，英文名为'RESID_ADDR_NAME'，类型为string，示例数据'辽宁省梧州市南湖刘街B座 132736'包含省、市、街道及门牌号，符合详细地址特征。在<configs>中'地址'类别对应的示例值为'江苏省徐州市泉山区金江街道汉中路604号'，与示例数据在结构和语义上高度一致，因此推荐为'地址'类别。",
        "category": "地址",
    },
    {
        "col": 34,
        "args": {},
        "name": "",
        "cname": "案别代码",
        "ename": "CASE_TYPE_CODE",
        "value": "4000000",
        "preview": "score: 90, reason: 字段示例数据'4000000'为纯数字字符串，且字段名为'案别代码'，结合字典名称'刑事案件分类与代码'，表明其为分类编码。虽然与'案件编号'等类别有语义关联，但示例数据仅为数字串，无明显编码结构特征（如字母、特定长度、校验位等），与预定义类别中'案件编号'（如JQ57848142）的格式不匹配，因此无法确定为特定类别，最符合的是'数字串'。",
        "category": "数字串",
    },
    {
        "col": 35,
        "args": {},
        "name": "",
        "cname": "案别名称",
        "ename": "CASCLA_NAME",
        "value": "音乐文章网站服务.",
        "preview": "score: 85, reason: 字段示例数据'音乐文章网站服务.'包含'文章'一词，且整体为一段描述性文本，符合'文章'类别的特征，与<configs>中'文章'条目的示例值'\"这是一段随机的文章文本内容.\"'在语义和形式上高度相似，尽管内容不完全一致，但整体属于非结构化文本描述，因此推荐为'文章'类别。",
        "category": "文章",
    },
    {
        "col": 36,
        "args": {},
        "name": "",
        "cname": "简要案情",
        "ename": "BRIEF_CASE",
        "value": "参加合作情况一样国际分析.事情文章积分类别出来地址.知道过程能力.操作类型为什联系.",
        "preview": "score: 90, reason: 字段中文名为'简要案情'，示例数据为一段无序的中文文本，包含多个语义片段，符合非结构化文本特征；与<configs>中'文章'条目的示例'这是一段随机的文章文本内容.'在内容形式和语义上高度相似，均为自然语言描述性文本，因此推荐为'文章'类别，置信度较高。",
        "category": "文章",
    },
    {
        "col": 37,
        "args": {},
        "name": "",
        "cname": "作案手段代码",
        "ename": "CRIM_MEANS_CHAR_CODE",
        "value": "",
        "preview": "score: 90, reason: 字段名为'作案手段代码'，类型为string，示例数据为空，但根据字段名称和常见数据编码规则，'作案手段代码'通常为数字编码（如01、02等），具有数字串特征。虽然无示例数据，但结合字段语义和常见编码模式，最符合'数字串'类别，且该类别在<configs>中存在，置信度较高。",
        "category": "数字串",
    },
    {
        "col": 38,
        "args": {},
        "name": "",
        "cname": "作案手段",
        "ename": "CRIM_MEANS_CHAR_NAME",
        "value": "",
        "preview": "score: 85, reason: 字段名为'作案手段'，类型为string，示例数据为空，但根据字段名称和语义，其内容可能为描述性文本，如'持刀抢劫'、'网络诈骗'等，这类内容具有随机性、非标准化特征，与<configs>中'随机串'的示例'出现这样当前以及.'在语义和模式上相似，均属于非结构化、非标准文本，因此推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 39,
        "args": {},
        "name": "",
        "cname": "作案工具代码",
        "ename": "CRIM_CRIM_TOOL_CODE",
        "value": "510100",
        "preview": "score: 85, reason: 字段示例数据'510100'为6位数字，符合编号类数据特征，且无明显语义含义；结合字段名'作案工具代码'和字典名称'涉案物品'，推测其为系统生成的唯一标识码，与'随机主键'类别中'c1331fd2af684b20857198c3a07a3764'这类无语义的随机字符串在模式上一致，虽非完全匹配，但最接近预定义类别中的'随机主键'。",
        "category": "随机主键",
    },
    {
        "col": 40,
        "args": {},
        "name": "",
        "cname": "作案工具",
        "ename": "CRIM_CRIM_TOOL_NAME",
        "value": "",
        "preview": "score: 85, reason: 字段名为'作案工具'，字段类型为string，示例数据为空，无法通过具体值判断。但'作案工具'属于非标准、非结构化信息，可能为任意描述性文本，与<configs>中'随机串'的语义（如'出现这样当前以及.'）相似，均为无固定模式的字符串，且无明确类别匹配，故推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 41,
        "args": {},
        "name": "",
        "cname": "选择地点",
        "ename": "CRIM_PLAC_PLAC_NAME",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'选择地点'，英文名为'CRIM_PLAC_PLAC_NAME'，结合字段类型为string且无其他明确标识，示例数据虽为空，但根据名称语义可推断为地理位置相关描述；在<configs>中'地址'类别对应示例为'江苏省徐州市泉山区金江街道汉中路604号'，具有明确的地理定位特征，与'选择地点'的语义高度匹配，因此推荐为'地址'类别。",
        "category": "地址",
    },
    {
        "col": 42,
        "args": {},
        "name": "",
        "cname": "其他信息",
        "ename": "REM",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'其他信息'，英文名为'REM'，类型为string，无明确语义描述，示例数据为空或未提供，无法匹配具体业务字段。结合其'其他'属性及无规律特征，最符合'随机串'类别中'出现这样当前以及.'这类无特定含义的随机文本特征，且在<configs>中存在对应条目，故推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 43,
        "args": {},
        "name": "",
        "cname": "办案单位代码",
        "ename": "CASE_ORGA_PSAG_CODE",
        "value": "",
        "preview": "score: 90, reason: 字段中文名为'办案单位代码'，英文名为'CASE_ORGA_PSAG_CODE'，类型为string，其语义指向某一单位的标识代码。在<configs>中'单位编号'的示例值为'JQ34709347'，符合以字母和数字组合的编码特征，与'办案单位代码'的命名和用途高度匹配，因此推荐为'单位编号'。",
        "category": "单位编号",
    },
    {
        "col": 44,
        "args": {},
        "name": "",
        "cname": "办案单位",
        "ename": "CASE_ORGA_PSAG",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'办案单位'，指向一个机构或单位的名称，结合字段英文名'CASE_ORGA_PSAG'暗示其为案件相关单位标识，且类型为string。在<configs>中'单位编号'的示例值为'JQ34709347'，具有类似编码特征（字母+数字组合），符合单位标识的常见格式。虽然'公司名称'也相关，但'单位编号'更强调编号属性，与'办案单位'作为管理或系统标识的用途更匹配。",
        "category": "单位编号",
    },
    {
        "col": 45,
        "args": {},
        "name": "",
        "cname": "信息来源",
        "ename": "INFO_SOUR_INFO_SOUR_DESC",
        "value": "",
        "preview": "score: 85, reason: 字段中文名为'信息来源'，虽名称不直接指向地址，但结合其英文名'INFO_SOUR_INFO_SOUR_DESC'及上下文语境，可能用于描述信息的来源类型，如'公安系统'、'互联网'等。在<configs>中'地址类型'的value为'其它'，其语义为一种分类标识，与'信息来源'作为分类标签的用途相符。尽管名称不完全匹配，但根据字段用途和分类逻辑，'地址类型'是唯一与'其它'这类分类标签语义一致的预定义类别。置信度较高，因无更精确匹配类别。",
        "category": "地址类型",
    },
    {
        "col": 46,
        "args": {},
        "name": "",
        "cname": "抓获时间",
        "ename": "CAPT_DATE",
        "value": "20250605",
        "preview": "score: 90, reason: 字段中文名为'抓获时间'，英文名为'CAPT_DATE'，类型为string，示例数据'20250605'为8位数字，格式为YYYYMMDD，符合日期格式。与<configs>中'当月日期'条目（value为'2025-06-05'）在时间语义和格式上高度一致，仅缺少分隔符，因此推荐为'当月日期'，置信度较高。",
        "category": "当月日期",
    },
]
test_right = [
    {
        "col": 1,
        "args": {},
        "name": "",
        "cname": "MD5",
        "ename": "MD_ID",
        "value": "0836b96919b579c792a255ca7ef3b0ae",
        "preview": "score: 98, reason: 字段中文名为'MD5'，英文名为'MD_ID'，示例数据'0836b96919b579c792a255ca7ef3b0ae'为32位十六进制字符，符合MD5哈希值的典型格式，与<configs>中'MD5'条目完全匹配。",
        "category": "MD5",
    },
    {
        "col": 2,
        "args": {},
        "name": "",
        "cname": "属性类型一",
        "ename": "FIRST_TYPE",
        "value": "D201005",
        "preview": "score: 85, reason: 字段示例数据'D201005'为字母与数字组合，无明显规律，不匹配身份证、车牌号、IMSI等特定格式的类别；其结构与预定义中'随机串'的示例'出现这样当前以及.'在语义上更接近，均为无明确语义的随机字符组合，故推荐为'随机串'类别，置信度较高。",
        "category": "随机串",
    },
    {
        "col": 3,
        "args": {},
        "name": "",
        "cname": "属性类型一的值",
        "ename": "FIRST_VALUE",
        "value": "13000010053",
        "preview": "score: 98, reason: 字段示例数据'13000010053'为纯数字字符串，长度为11位，无明显业务含义或格式特征（如身份证、手机号、车牌号等），与<configs>中'数字串'类别示例'264280'高度一致，符合纯数字字符串的特征，因此推荐为'数字串'类别。",
        "category": "数字串",
    },
    {
        "col": 4,
        "args": {},
        "name": "",
        "cname": "属性类型二",
        "ename": "SECOND_TYPE",
        "value": "D201005",
        "preview": "score: 85, reason: 字段示例数据'D201005'由字母和数字混合组成，长度较短，无明显规律，不匹配身份证、车牌号、手机号等特定格式的证件或编号，也非标准日期、时间、邮箱等常见类型，符合'随机串'的特征，与<configs>中'随机串'的示例'出现这样当前以及.'在模式上相似，均为无明确语义的字符组合，因此推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 5,
        "args": {},
        "name": "",
        "cname": "属性类型二的值",
        "ename": "SECOND_VALUE",
        "value": "14520628802",
        "preview": "score: 98, reason: 字段示例数据'14520628802'为纯数字字符串，长度为11位，无明显业务含义（如身份证、手机号等），且与预定义类别中'数字串'的示例值特征一致，未发现符合其他特定类别的依据，故推荐为'数字串'。",
        "category": "数字串",
    },
    {
        "col": 6,
        "args": {},
        "name": "",
        "cname": "关系类型",
        "ename": "REL_TYPE",
        "value": "B27",
        "preview": "score: 85, reason: 字段名为'关系类型'，示例数据为'B27'，该数据为字母与数字的组合，长度较短，无明显语义特征，不符合常见标识符（如身份证、车牌号等）的固定格式，也不符合日期、数字串、邮箱等典型模式，与'随机串'类别中示例'出现这样当前以及.'的无规律性特征相似，因此推荐为'随机串'，置信度较高。",
        "category": "随机串",
    },
    {
        "col": 7,
        "args": {},
        "name": "",
        "cname": "来源",
        "ename": "SOURCE",
        "value": "137C005",
        "preview": "score: 90, reason: 字段示例数据'137C005'为字母与数字组合，长度较短且无明显规律，符合随机生成主键的特征；虽然'137C005'不完全匹配'随机主键'的示例（如c1331fd2af684b20857198c3a07a3764），但其结构（字母+数字混合、无固定格式）与'随机主键'类别高度一致，且在<configs>中未发现更匹配的类别，故推荐为'随机主键'。",
        "category": "随机主键",
    },
    {
        "col": 8,
        "args": {},
        "name": "",
        "cname": "提取规则",
        "ename": "RULE",
        "value": "",
        "preview": "score: 85, reason: 字段名为'RULE'，类型为string，示例数据为空，但'提取规则'这一中文名暗示其内容可能是用于定义数据提取逻辑的字符串，可能包含不规则的文本或表达式，与'随机串'类别中'出现这样当前以及.'这类无规律文本具有相似性，且无明确结构，符合'随机串'的语义特征。尽管'规则'可能指向特定格式，但因无实际示例数据，无法判断其是否为标准规则，故推荐为'随机串'。",
        "category": "随机串",
    },
    {
        "col": 9,
        "args": {},
        "name": "",
        "cname": "提取原因",
        "ename": "REASON",
        "value": '[{"mrk":"吴芳","dir":"1","status":"2"}]',
        "preview": 'score: 85, reason: 字段示例数据为JSON格式的字符串，内容为{"mrk":"吴芳","dir":"1","status":"2"}，具有结构化但非标准格式的特征，其内容为随机组合的键值对，无明显语义规律，与预定义类别中\'随机串\'的示例\'出现这样当前以及.\'在模式和语义上相似，均为非标准、无明确业务含义的字符串，因此推荐为\'随机串\'类别。',
        "category": "随机串",
    },
    {
        "col": 10,
        "args": {},
        "name": "",
        "cname": "首次关联时间",
        "ename": "FIRST_TIME",
        "value": "-1",
        "preview": "score: 90, reason: 字段名为'首次关联时间'，英文名为'FIRST_TIME'，类型为'long'，示例数据为'-1'，符合时间绝对秒（Unix timestamp）的特征，尽管值为-1可能表示无效或未关联状态，但其数据类型和命名模式与'时间绝对秒'类别高度一致。【时间字段-由程序强制设置规则为当前时间绝对秒】",
        "category": "当前时间绝对秒",
    },
    {
        "col": 11,
        "args": {},
        "name": "",
        "cname": "最晚关联时间",
        "ename": "LAST_TIME",
        "value": "-1",
        "preview": "score: 90, reason: 字段英文名为'LAST_TIME'，类型为'long'，示例数据为'-1'，符合时间绝对秒（Unix时间戳）的特征，尽管值为负数，但仍可能表示一个时间戳（如在某些系统中使用负数表示特定时间点）。在<configs>中'时间绝对秒'的value为整数，与该字段类型和示例数据高度匹配，因此推荐为'时间绝对秒'。【时间字段-由程序强制设置规则为当前时间绝对秒】",
        "category": "当前时间绝对秒",
    },
    {
        "col": 12,
        "args": {},
        "name": "",
        "cname": "关系次数",
        "ename": "COUNT",
        "value": "1",
        "preview": "score: 98, reason: 字段名为'关系次数'，示例数据为'1'，数据类型为long，表示一个整数数值，符合'数字串'的特征。虽然可能与'数量'相关，但预定义类别中无'数量'类别，而'数字串'是最匹配的类别，其示例'264280'与'1'同为数字形式，语义和模式一致。",
        "category": "数字串",
    },
]
s, m, r = compare_task_rule(left_rule_array=test_left, right_rule_array=test_right)
logger.info(f"status={s}")
logger.info(f"message={m}")
logger.info(f"result={json.dumps(r, ensure_ascii=False)}")
