version: "3"

services:
  server:
    image: llm_server_py313_env:1.0.0
    container_name: DataForgeServer
    hostname: DataForgeServer
    restart: unless-stopped
    privileged: true
    working_dir: /app
    command: bash -c "python -m serve"
    networks:
      harbor_net:
    ports:
      - "25702:25702"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./database:/app/database
      - ./logs:/app/logs
      - ./database_models:/app/database_models
      - ./agent:/app/agent
      - ./app_data_gen:/app/app_data_gen
      - ./app_table_gen:/app/app_table_gen
      - ./cruds:/app/cruds
      - ./common:/app/common
      - ./server:/app/server
      - ./utils:/app/utils
      - ./config.py:/app/config.py
      - ./serve.py:/app/serve.py
      - ./.env:/app/.env
    environment:
      - TZ=Asia/Shanghai
      # 日志级别
      - LOG_LEVEL=INFO
      - SQLALCHEMY_ECHO=false
      # 数据默认保留时间
      - DATA_EXPIRED_DAY=30
      # 部署环境的服务器IP
      - SERVER_HOST=10.1.2.132
      - SERVER_PORT=25702
      - APOLLO_WEB_IP=172.21.5.130
      - APOLLO_WEB_PORT=8070

  data_gen_chat:
    image: llm_server_py313_env:1.0.0
    container_name: DFDataGenApp
    hostname: DFDataGenApp
    restart: unless-stopped
    privileged: true
    working_dir: /app
    command: bash -c "python -m app_data_gen.run"
    networks:
      harbor_net:
    ports:
      - "9801:9801"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./database:/app/database
      - ./logs:/app/logs
      - ./database_models:/app/database_models
      - ./agent:/app/agent
      - ./app_data_gen:/app/app_data_gen
      - ./cruds:/app/cruds
      - ./common:/app/common
      - ./utils:/app/utils
      - ./config.py:/app/config.py
      - ./.env:/app/.env
      - ./.chainlit:/app/.chainlit
    environment:
      - TZ=Asia/Shanghai
      # 日志级别
      - LOG_LEVEL=INFO
      - SQLALCHEMY_ECHO=false
      # 数据默认保留时间
      - DATA_EXPIRED_DAY=30

  table_gen_chat:
    image: llm_server_py313_env:1.0.0
    container_name: DFTableGenApp
    hostname: DFTableGenApp
    restart: unless-stopped
    privileged: true
    working_dir: /app
    command: bash -c "python -m app_table_gen.run"
    networks:
      harbor_net:
    ports:
      - "9802:9802"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./database:/app/database
      - ./logs:/app/logs
      - ./database_models:/app/database_models
      - ./agent:/app/agent
      - ./app_table_gen:/app/app_table_gen
      - ./cruds:/app/cruds
      - ./common:/app/common
      - ./utils:/app/utils
      - ./config.py:/app/config.py
      - ./.env:/app/.env
      - ./.chainlit:/app/.chainlit
    environment:
      - TZ=Asia/Shanghai
      # 日志级别
      - LOG_LEVEL=INFO
      - SQLALCHEMY_ECHO=false
      # 数据默认保留时间
      - DATA_EXPIRED_DAY=30

  sql_mode_data_gen_chat:
    image: llm_server_py313_env:1.0.0
    container_name: SQLModeDFDataGenApp
    hostname: DFDataGenApp
    restart: unless-stopped
    privileged: true
    working_dir: /app
    command: bash -c "python -m app_sql_mode_data_gen.run"
    networks:
      harbor_net:
    ports:
      - "9803:9803"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./database:/app/database
      - ./logs:/app/logs
      - ./database_models:/app/database_models
      - ./agent:/app/agent
      - ./app_sql_mode_data_gen:/app/app_sql_mode_data_gen
      - ./cruds:/app/cruds
      - ./common:/app/common
      - ./utils:/app/utils
      - ./config.py:/app/config.py
      - ./.env:/app/.env
      - ./.chainlit:/app/.chainlit
    environment:
      - TZ=Asia/Shanghai
      # 日志级别
      - LOG_LEVEL=INFO
      - SQLALCHEMY_ECHO=false
      # 数据默认保留时间
      - DATA_EXPIRED_DAY=30


  fmdb_insert_sql_gen_chat:
    image: llm_server_py313_env:1.0.0
    container_name: FMDBInsertSQLGenApp
    hostname: FMDBInsertSQLGenApp
    restart: unless-stopped
    privileged: true
    working_dir: /app
    command: bash -c "python -m app_fmdb_insert_sql_gen.run"
    networks:
      harbor_net:
    ports:
      - "9804:9804"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data
      - ./database:/app/database
      - ./logs:/app/logs
      - ./database_models:/app/database_models
      - ./agent:/app/agent
      - ./app_fmdb_insert_sql_gen:/app/app_fmdb_insert_sql_gen
      - ./cruds:/app/cruds
      - ./common:/app/common
      - ./utils:/app/utils
      - ./config.py:/app/config.py
      - ./.env:/app/.env
      - ./.chainlit:/app/.chainlit
    environment:
      - TZ=Asia/Shanghai
      # 日志级别
      - LOG_LEVEL=INFO
      - SQLALCHEMY_ECHO=false
      # 数据默认保留时间
      - DATA_EXPIRED_DAY=30

  caddy:
    image: caddy:2-alpine
    container_name: DFCaddy
    restart: unless-stopped
    networks:
      harbor_net:
    ports:
      - "80:80"
      - "443:80"
      - "8443:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/logs:/var/log/caddy
    depends_on:
      - fmdb_insert_sql_gen_chat
    environment:
      - TZ=Asia/Shanghai



networks:
  harbor_net:
    external: true


