"""init db

Revision ID: 1f08e516b0b5
Revises: 
Create Date: 2025-09-11 16:36:13.363309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f08e516b0b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_info',
    sa.Column('env_name', sa.String(length=128), nullable=False, comment='环境名称'),
    sa.Column('apollo_web_ip', sa.String(length=64), nullable=True, comment='阿波罗界面IP'),
    sa.Column('local_city_code', sa.String(length=6), nullable=True, comment='地市编码: LOCAL_CITYCODE'),
    sa.Column('bdp_web_ip', sa.String(length=128), nullable=True, comment='BDPWeb角色IP: BDPWeb_ip'),
    sa.Column('pangu_web_ip', sa.String(length=128), nullable=True, comment='盘古界面IP: pangu_web_ip'),
    sa.Column('metadata_db_ip', sa.String(length=64), nullable=True, comment='盘古元数据库IP: Metadata_Dbn_ip'),
    sa.Column('metadata_db_port', sa.Integer(), nullable=True, comment='盘古元数据库端口: Metadata_Dbn_dbPort'),
    sa.Column('metadata_db_user', sa.String(length=128), nullable=True, comment='盘古元数据库用户名: Metadata_Dbn_dbUser'),
    sa.Column('metadata_db_password', sa.String(length=128), nullable=True, comment='盘古元数据库密码: Metadata_Dbn_dbPassword'),
    sa.Column('metadata_db_name', sa.String(length=128), nullable=True, comment='盘古数据库名称: Metadata_Dbn_dbName'),
    sa.Column('tre_domain_data_bdp_web_ip', sa.String(length=128), nullable=True, comment='数据域单独的bdp web ip'),
    sa.Column('tre_domain_data_ip', sa.String(length=128), nullable=True, comment='数据域管理系统的IP: TRE_DOMAIN_DATA_ip'),
    sa.Column('other_configs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='其他配置信息'),
    sa.Column('env_hash', sa.String(length=72), nullable=True, comment='环境配置HASH, md5(除env_name, status的所有字段), 用于比较环境配置是否相同'),
    sa.Column('status', sa.Enum('enable', 'disable', 'retired', 'new', name='environmentstatus'), nullable=False, comment='状态位'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('env_name', name='uuid_uk'),
    comment='版本环境信息'
    )
    op.create_table('field_dg_rule_cache',
    sa.Column('uuid', sa.String(length=72), nullable=False, comment='规则唯一ID, md5(ename+cname+description+field_type_name)'),
    sa.Column('scope', sa.String(length=256), nullable=True, comment='领域'),
    sa.Column('ename', sa.String(length=512), nullable=False, comment='字段英文名称'),
    sa.Column('cname', sa.String(length=512), nullable=True, comment='字段出现次数最多的中文名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='字段描述'),
    sa.Column('field_type_name', sa.String(length=128), nullable=True, comment='字段类型'),
    sa.Column('dg_rule', sa.JSON(), nullable=False, comment='DG规则配置'),
    sa.Column('example_data', sa.Text(), nullable=True, comment='样例数据'),
    sa.Column('ttl', sa.Integer(), nullable=False, comment='缓存规则过期时间，默认7天'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ename', 'uuid', name='ename_uuid_unique'),
    sa.UniqueConstraint('uuid', name='uuid'),
    comment='字段的DG规则配置缓存'
    )
    op.create_index(op.f('ix_field_dg_rule_cache_ename'), 'field_dg_rule_cache', ['ename'], unique=False)
    op.create_table('pangu_dict_info',
    sa.Column('uuid', sa.BigInteger(), nullable=False, comment='字典的唯一编码'),
    sa.Column('dictkey_with_nlevel', sa.String(length=128), nullable=False, comment='字段存储的字典key'),
    sa.Column('dict_category_code', sa.String(length=128), nullable=False, comment='字典类别key'),
    sa.Column('dict_category', sa.String(length=384), nullable=False, comment='字典类别名称'),
    sa.Column('dict_level', sa.Integer(), nullable=False, comment='字典层级'),
    sa.Column('dict_id', sa.String(length=128), nullable=False, comment='字典项编码'),
    sa.Column('dict_name', sa.Text(), nullable=False, comment='字典项名称'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', 'dictkey_with_nlevel', name='dictkey_with_nlevel_uuid_uk'),
    sa.UniqueConstraint('uuid', name='dict_uk'),
    comment='盘古字典'
    )
    op.create_table('recommend_pangu_field_info',
    sa.Column('ename', sa.String(length=512), nullable=True, comment='字段英文名称'),
    sa.Column('cname', sa.String(length=512), nullable=True, comment='字段出现次数最多的中文名称'),
    sa.Column('cname_count', sa.Integer(), nullable=True, comment='该字段在所有表中的总数'),
    sa.Column('cname_percentage', sa.Float(), nullable=True, comment='字段出现次数最多的中文名称占字段总数的百分比'),
    sa.Column('identifier', sa.String(length=512), nullable=True, comment='出现次数最多的数据项标识符'),
    sa.Column('identifier_count', sa.Integer(), nullable=True, comment='最多的数据项标识符最多出现次数'),
    sa.Column('identifier_percentage', sa.Float(), nullable=True, comment='出现次数最多的数据项标识符占比'),
    sa.Column('description', sa.Text(), nullable=True, comment='出现次数最多的字段描述，对应COMMENT'),
    sa.Column('description_count', sa.Integer(), nullable=True, comment='字段描述出现最多次数'),
    sa.Column('description_percentage', sa.Float(), nullable=True, comment='出现最多次数字段描述占比'),
    sa.Column('field_type_name', sa.String(length=128), nullable=True, comment='出现次数最多的字段类型'),
    sa.Column('field_type_count', sa.Integer(), nullable=True, comment='字段类型出现次数'),
    sa.Column('field_type_percentage', sa.Float(), nullable=True, comment='字段类型出现次数占比'),
    sa.Column('dictkey', sa.String(length=255), nullable=True, comment='出现次数最多的字典关联ID及层级 关联字典表BASE_DD_TAB的PARENTID和NLEVEL 格式PARENTID:NLEVEL'),
    sa.Column('dictkey_count', sa.Integer(), nullable=True, comment='字典关联ID及层级出现次数'),
    sa.Column('dictkey_percentage', sa.Float(), nullable=True, comment='字典关联ID及层级出现次数占比'),
    sa.Column('field_length', sa.String(length=128), nullable=True, comment='出现次数最多的字段长度'),
    sa.Column('field_length_count', sa.Integer(), nullable=True, comment='字段长度出现次数'),
    sa.Column('field_length_percentage', sa.Float(), nullable=True, comment='字段长度出现次数占比'),
    sa.Column('element_code_name', sa.String(length=512), nullable=True, comment='出现次数最多的数据元标示符名称'),
    sa.Column('element_code_count', sa.Integer(), nullable=True, comment='数据元标示符名称出现次数'),
    sa.Column('element_code_name_percentage', sa.Float(), nullable=True, comment='数据元标示符名称出现次数占比'),
    sa.Column('determiner_code_name', sa.String(length=512), nullable=True, comment='出现次数最多的限定词标示符'),
    sa.Column('determiner_code_count', sa.Integer(), nullable=True, comment='限定词标示符出现次数'),
    sa.Column('determiner_code_percentage', sa.Float(), nullable=True, comment='限定词标示符出现次数占比'),
    sa.Column('structure_type', sa.Integer(), nullable=True, comment='出现次数最多的字段结构化类型，0(默认)：结构化；1：非结构化'),
    sa.Column('structure_type_count', sa.Integer(), nullable=True, comment='字段结构化类型出现次数'),
    sa.Column('structure_type_percentage', sa.Float(), nullable=True, comment='字段结构化类型出现次数占比'),
    sa.Column('is_multi_value', sa.Integer(), nullable=True, comment='出现次数最多的是否是多值列 1：是；0：否'),
    sa.Column('is_multi_value_count', sa.Integer(), nullable=True, comment='是否是多值列出现次数'),
    sa.Column('is_multi_value_percentage', sa.Float(), nullable=True, comment='是否是多值列出现次数占比'),
    sa.Column('is_required', sa.Integer(), nullable=True, comment='出现次数最多的是否必填 1-必填 0-非必填'),
    sa.Column('is_required_count', sa.Integer(), nullable=True, comment='是否必填出现次数'),
    sa.Column('is_required_percentage', sa.Float(), nullable=True, comment='是否必填出现次数占比'),
    sa.Column('core_flag', sa.String(length=128), nullable=True, comment='出现次数最多的是否核心字段  1-核心  0-普通'),
    sa.Column('core_flag_count', sa.Integer(), nullable=True, comment='是否核心字段出现次数'),
    sa.Column('core_flag_percentage', sa.Float(), nullable=True, comment='是否核心字段出现次数占比'),
    sa.Column('example_data', sa.Text(), nullable=True, comment='样例数据'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='盘古字段元数据推荐'
    )
    op.create_index(op.f('ix_recommend_pangu_field_info_ename'), 'recommend_pangu_field_info', ['ename'], unique=True)
    op.create_table('table_example_data_info',
    sa.Column('uuid', sa.String(length=72), nullable=False, comment='数据唯一ID, md5(example_data)'),
    sa.Column('table_uuid', sa.String(length=72), nullable=False, comment='表唯一ID'),
    sa.Column('example_data', sa.JSON(), nullable=True, comment='表样例数据'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uk_tb_example'),
    comment='表样例数据信息'
    )
    op.create_table('table_meta_data_info',
    sa.Column('uuid', sa.String(length=72), nullable=False, comment='表唯一ID, md5(table_en_name+source+env_name)'),
    sa.Column('table_en_name', sa.String(length=128), nullable=False, comment='表英文名称'),
    sa.Column('table_cn_name', sa.String(length=256), nullable=False, comment='表中文名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='表描述'),
    sa.Column('position_type', sa.String(length=128), nullable=True, comment='数据库类型'),
    sa.Column('storage_type', sa.String(length=128), nullable=True, comment='表数据格式'),
    sa.Column('table_fields', sa.JSON(), nullable=False, comment='表字段信息'),
    sa.Column('area_code', sa.String(length=64), nullable=True, comment='来源地市编码'),
    sa.Column('area_name', sa.String(length=64), nullable=True, comment='来源地市名称'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uk_tb_meta'),
    comment='表元数据信息'
    )
    op.create_table('task_info',
    sa.Column('task_uuid', sa.String(length=72), nullable=False, comment='任务唯一ID, 与session_uuid, trace_uuid一致'),
    sa.Column('table_en_name', sa.String(length=128), nullable=False, comment='表英文名称'),
    sa.Column('data_row_count', sa.Integer(), nullable=True, comment='任务生成的数据条数'),
    sa.Column('user_intent', sa.JSON(), nullable=True, comment='用户意图'),
    sa.Column('mode', sa.Integer(), nullable=True, comment='任务模式[0:未知 1: 元数据模式 2: SQL解析模式]'),
    sa.Column('client_ip', sa.String(length=15), nullable=True, comment='客户端IP'),
    sa.Column('task_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='创建任务请求的请求体JSON'),
    sa.Column('rule_name', sa.String(length=56), nullable=True, comment='任务规则名称'),
    sa.Column('task_rule', sa.JSON(), nullable=True, comment='任务规则配置JSON'),
    sa.Column('dg_task_status', sa.Integer(), nullable=True, comment='DG任务状态: 0正常,1异常,-1未知'),
    sa.Column('dg_task_message', sa.Text(), nullable=True, comment='DG任务状态信息'),
    sa.Column('dg_task_id', sa.String(length=36), nullable=True, comment='DG的任务ID'),
    sa.Column('dg_task_edit_url', sa.Text(), nullable=True, comment='DG任务的编辑URL'),
    sa.Column('dg_task_rule_data_preview', sa.JSON(), nullable=True, comment='DG规则的预览数据'),
    sa.Column('dg_task_duration', sa.String(length=56), nullable=True, comment='DG任务耗时'),
    sa.Column('user_modified_rules', sa.JSON(), nullable=True, comment='用户修改的字段规则'),
    sa.Column('env_name', sa.String(length=128), nullable=True, comment='环境名称'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_uuid', 'table_en_name', name='task_uuid_table_en_name_unique'),
    comment='任务信息表'
    )
    op.create_index('idx_table_en_name', 'task_info', ['table_en_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_en_name', table_name='task_info')
    op.drop_table('task_info')
    op.drop_table('table_meta_data_info')
    op.drop_table('table_example_data_info')
    op.drop_index(op.f('ix_recommend_pangu_field_info_ename'), table_name='recommend_pangu_field_info')
    op.drop_table('recommend_pangu_field_info')
    op.drop_table('pangu_dict_info')
    op.drop_index(op.f('ix_field_dg_rule_cache_ename'), table_name='field_dg_rule_cache')
    op.drop_table('field_dg_rule_cache')
    op.drop_table('environment_info')
    # ### end Alembic commands ###
