"""update task field

Revision ID: 3872276905e1
Revises: f71f43ef4aba
Create Date: 2025-10-28 14:16:30.047793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3872276905e1'
down_revision = 'f71f43ef4aba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('dg_task_type', sa.String(length=56), nullable=True, comment='DG任务类型'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_info', 'dg_task_type')
    # ### end Alembic commands ###
