"""chg pangu_dict unique key

Revision ID: 3d386a87109d
Revises: d74c56702f49
Create Date: 2025-08-13 09:52:40.602822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d386a87109d'
down_revision = 'd74c56702f49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pangu_dict_info_uuid_key', 'pangu_dict_info', type_='unique')
    op.create_unique_constraint('dictkey_with_nlevel_uuid_unique', 'pangu_dict_info', ['dictkey_with_nlevel', 'uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uuid', 'pangu_dict_info', type_='unique')
    op.drop_constraint('dictkey_with_nlevel_uuid_unique', 'pangu_dict_info', type_='unique')
    # ### end Alembic commands ###
