"""add dg_rule_cache

Revision ID: 54a611fdbdca
Revises: 3c389ea4e6d8
Create Date: 2025-08-11 14:57:07.377173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a611fdbdca'
down_revision = '3c389ea4e6d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_dg_rule_cache',
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='规则唯一ID, md5(ename+cname+description+field_type_name)'),
    sa.Column('ename', sa.String(length=512), nullable=True, comment='字段英文名称'),
    sa.Column('cname', sa.String(length=512), nullable=True, comment='字段出现次数最多的中文名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='字段描述'),
    sa.Column('field_type_name', sa.String(length=128), nullable=True, comment='字段类型'),
    sa.Column('dg_rule', sa.JSON(), nullable=False, comment='DG规则配置'),
    sa.Column('example_data', sa.Text(), nullable=True, comment='样例数据'),
    sa.Column('ttl', sa.Integer(), nullable=False, comment='缓存规则过期时间，默认7天'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uuid'),
    comment='字段的DG规则配置缓存'
    )
    op.create_index(op.f('ix_field_dg_rule_cache_ename'), 'field_dg_rule_cache', ['ename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_dg_rule_cache_ename'), table_name='field_dg_rule_cache')
    op.drop_table('field_dg_rule_cache')
    # ### end Alembic commands ###
