"""init db

Revision ID: 5c7acde71f38
Revises: 
Create Date: 2025-05-15 16:23:25.845267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7acde71f38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_meta_data_info',
    sa.Column('uuid', sa.String(length=36), nullable=False, comment='表唯一一ID, md5(table_en_name+source_code)'),
    sa.Column('table_en_name', sa.String(length=128), nullable=False, comment='表英文名称'),
    sa.Column('table_cn_name', sa.String(length=256), nullable=False, comment='表中文名称'),
    sa.Column('table_description', sa.Text(), nullable=True, comment='表描述'),
    sa.Column('position_type', sa.String(length=128), nullable=True, comment='数据库类型'),
    sa.Column('storage_type', sa.String(length=128), nullable=True, comment='表数据格式'),
    sa.Column('fields_json', sa.JSON(), nullable=False, comment='表字段信息'),
    sa.Column('area_code', sa.String(length=64), nullable=True, comment='地市来源'),
    sa.Column('source', sa.String(length=64), nullable=True, comment='数据来源'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid', name='uk_environment'),
    comment='表元数据信息'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_meta_data_info')
    # ### end Alembic commands ###
