"""add task_info

Revision ID: 65867bfc7c10
Revises: 3d386a87109d
Create Date: 2025-09-01 14:18:38.099370

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "65867bfc7c10"
down_revision = "3d386a87109d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_info",
        sa.Column(
            "task_uuid",
            sa.String(length=36),
            nullable=False,
            comment="任务唯一ID, 与session_uuid, trace_uuid一致",
        ),
        sa.Column(
            "table_en_name", sa.String(length=128), nullable=False, comment="表英文名称"
        ),
        sa.Column(
            "data_row_count", sa.Integer(), nullable=True, comment="任务生成的数据条数"
        ),
        sa.Column("source", sa.String(length=64), nullable=True, comment="数据来源"),
        sa.Column("client_ip", sa.String(length=15), nullable=True, comment="客户端IP"),
        sa.Column(
            "task_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="创建任务请求的请求体JSON",
        ),
        sa.Column(
            "rule_name", sa.String(length=56), nullable=True, comment="任务规则名称"
        ),
        sa.Column("task_rule", sa.JSON(), nullable=True, comment="任务规则配置JSON"),
        sa.Column(
            "dg_task_name", sa.String(length=128), nullable=True, comment="DG的任务名称"
        ),
        sa.Column(
            "dg_task_status", sa.Integer(), nullable=True, comment="0正常,1异常,-1未知"
        ),
        sa.Column(
            "dg_task_id", sa.String(length=36), nullable=True, comment="DG的任务ID"
        ),
        sa.Column(
            "dg_task_edit_url", sa.Text(), nullable=True, comment="DG任务的编辑URL"
        ),
        sa.Column(
            "dg_task_download_url",
            sa.Text(),
            nullable=True,
            comment="DG任务结果的下载URL",
        ),
        sa.Column(
            "dg_task_duration", sa.Integer(), nullable=True, comment="DG任务耗时"
        ),
        sa.Column(
            "user_modified_rules",
            sa.JSON(),
            nullable=True,
            comment="用户修改的字段规则",
        ),
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主键"
        ),
        sa.Column("remark", sa.Text(), nullable=True, comment="备注"),
        sa.Column("create_time", sa.DateTime(), nullable=False, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=False, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_uuid", name="task_uuid_unique"),
        comment="任务信息表",
    )
    op.create_index("idx_table_en_name", "task_info", ["table_en_name"], unique=False)
    op.add_column(
        "field_dg_rule_cache",
        sa.Column("scope", sa.String(length=256), nullable=True, comment="领域"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field_dg_rule_cache", "scope")
    op.drop_index("idx_table_en_name", table_name="task_info")
    op.drop_table("task_info")
    # ### end Alembic commands ###
