"""chg task_uuid length 36 to 72

Revision ID: 9d47d99d7bfc
Revises: b63d69d11082
Create Date: 2025-10-13 16:09:17.748032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d47d99d7bfc'
down_revision = 'b63d69d11082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_info', 'task_uuid',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=72),
               existing_comment='任务唯一ID, 与session_uuid, trace_uuid一致',
               existing_nullable=False)
    op.alter_column('task_info', 'parent_dg_task_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=72),
               existing_comment='父任务的DG的任务ID, AI创建的任务人工修改后会有此信息',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_info', 'parent_dg_task_id',
               existing_type=sa.String(length=72),
               type_=sa.VARCHAR(length=36),
               existing_comment='父任务的DG的任务ID, AI创建的任务人工修改后会有此信息',
               existing_nullable=True)
    op.alter_column('task_info', 'task_uuid',
               existing_type=sa.String(length=72),
               type_=sa.VARCHAR(length=36),
               existing_comment='任务唯一ID, 与session_uuid, trace_uuid一致',
               existing_nullable=False)
    # ### end Alembic commands ###
