"""task t add parent field

Revision ID: b63d69d11082
Revises: 714e0b3745e5
Create Date: 2025-09-17 16:23:33.122153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63d69d11082'
down_revision = '714e0b3745e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('parent_dg_task_id', sa.String(length=36), nullable=True, comment='父任务的DG的任务ID, AI创建的任务人工修改后会有此信息'))
    op.add_column('task_info', sa.Column('parent_rule_name', sa.String(length=128), nullable=True, comment='父任务规则名称, AI创建的任务人工修改后会有此信息'))
    op.alter_column('task_info', 'task_uuid',
               existing_type=sa.VARCHAR(length=72),
               type_=sa.String(length=36),
               existing_comment='任务唯一ID, 与session_uuid, trace_uuid一致',
               existing_nullable=False)
    op.alter_column('task_info', 'rule_name',
               existing_type=sa.VARCHAR(length=56),
               type_=sa.String(length=128),
               existing_comment='任务规则名称',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_info', 'rule_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=56),
               existing_comment='任务规则名称',
               existing_nullable=True)
    op.alter_column('task_info', 'task_uuid',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=72),
               existing_comment='任务唯一ID, 与session_uuid, trace_uuid一致',
               existing_nullable=False)
    op.drop_column('task_info', 'parent_rule_name')
    op.drop_column('task_info', 'parent_dg_task_id')
    # ### end Alembic commands ###
