"""chg task_info add update and del parent

Revision ID: f71f43ef4aba
Revises: 9d47d99d7bfc
Create Date: 2025-10-17 16:19:39.167215

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f71f43ef4aba'
down_revision = '9d47d99d7bfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('update_task_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='任务更新后的规则配置JSON'))
    op.alter_column('task_info', 'task_rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='任务创建时的初始规则配置JSON',
               existing_comment='任务规则配置JSON',
               existing_nullable=True)
    op.drop_column('task_info', 'parent_rule_name')
    op.drop_column('task_info', 'parent_dg_task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_info', sa.Column('parent_dg_task_id', sa.VARCHAR(length=72), autoincrement=False, nullable=True, comment='父任务的DG的任务ID, AI创建的任务人工修改后会有此信息'))
    op.add_column('task_info', sa.Column('parent_rule_name', sa.VARCHAR(length=128), autoincrement=False, nullable=True, comment='父任务规则名称, AI创建的任务人工修改后会有此信息'))
    op.alter_column('task_info', 'task_rule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='任务规则配置JSON',
               existing_comment='任务创建时的初始规则配置JSON',
               existing_nullable=True)
    op.drop_column('task_info', 'update_task_rule')
    # ### end Alembic commands ###
